### ISSUE TITLE
hi why use load_state_dict twice?

### ISSUE THREAD

**Issue by 2018hello** [zhouyuangan/SE_DenseNet#2]
hi
I see in se_densenet_full.py, it use model.load_state_dict(state_dict, strict=is_strict)
And in test_se_densenet.py, it use 
model = se_densenet121(pretrained=pretrained)
        net_state_dict = {key: value for key, value in model_zoo.load_url("https://download.pytorch.org/models/densenet121-a639ec97.pth").items()}
        model.load_state_dict(net_state_dict, strict=False)
why?

**Comment by zhouyuangan** [comment]
@2018hello It's redundant codes while model instance just need load weight file only once, please remove redundant codes, I will take it if you can make a pull requests.
