### ISSUE TITLE
Amount of parameters

### ISSUE THREAD

**Issue by AldusLorde** [zhouyuangan/SE_DenseNet#4]
Hi) Thank you for your great work!
Could you show an amount of model parameters? I'm trying to implement SE-DenseNet from the scratch for my diploma work and I am not sure that my SE implementation is correct (it adds more than 3 millions parameters...)

**Comment by zhouyuangan** [comment]
Hi, @AldusLorde , thank you for your issue, I have some experiences in building the light-weight model, I'd like to use [this tool](https://github.com/zhouyuangan/flops-counter.pytorch) when I determine to remove some heavy layers in CNN module.  Please star it if this tool is helpful to you, thanks again.
